## Set the API endpoint used to create the Deployment resource.
apiVersion: apps/v1
## Define the type of the resource.
kind: Deployment
## Set the parameters that make the object identifiable, such as its name, namespace, and labels.
metadata:
  labels:
    app: techtrends
  namespace: {{.Values.namespace.name}}
  name: techtrends

## Define the desired configuration for the Deployment resource.
spec:
  ## Set the number of replicas.
  replicas: {{.Values.replicaCount}}
  ## Identify the pods managed by this Deployment using the following selectors.
  selector:
    matchLabels:
      app: techtrends
  ## Set the configuration for the pods.
  template:
    ## Define the identifiable metadata for the pods.
    metadata:
      labels:
        app: techtrends
    ## Define the desired state of the pod configuration.
    spec:
      ## Set the image to be executed inside the container
      containers:
      - image: {{.Values.image.repository}}:{{.Values.image.tag}}
        name: techtrends
        imagePullPolicy: {{.Values.image.pullPolicy}}
        ## Expose the port the container is listening on.
        ports:
          - containerPort: {{.Values.containerPort}}
        ## Define the rules for the liveness probes.
        livenessProbe:
          httpGet:
            path: {{.Values.livenessProbe.path}}
            port: {{.Values.containerPort}}
        ## Define the rules for the readiness probes.
        readinessProbe:
          httpGet:
            path: {{.Values.readinessProbe.path}}
            port: {{.Values.containerPort}}
        ## Set the resource requests and limits for an application.
        resources:
          requests:
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
        