#  name - "TechTrends - Package with Docker"
name: TechTrends - Package with Docker

#  Trigger on every push to the main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    # Run the action on the ubuntu-latest operating system
    runs-on: ubuntu-latest
    
    steps:
    # Use the Build and Push Docker images(https://github.com/marketplace/actions/build-and-push-docker-images) upstream GitHub Action as the basis
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        # Context should be set to the project directory(https://github.com/udacity/nd064_course_1/tree/main/project).
        context: "{{defaultContext}}:project"
        # Reference the Dockerfile for TechTrends application
        file: Dockerfile
        # Push the image to DockerHub with the tag techtrends:latest
        push: true
        tags: techtrends:latest
        